name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build master branch
    permissions: write-all
    runs-on: ubuntu-22.04

    

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 21

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Build Docker image
        run: docker build -t tradinggamedocker .

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: univ-smb-m1-isc-2023/tradinggame-web/main
          tags: latest

