name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build master branch
    runs-on: ubuntu-22.04

    permissions:
      contents: read
      packages: write
      actions: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Build Docker image
        run: docker build -t tradinggamedocker .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag Docker image
        run: docker tag tradinggamedocker docker.pkg.github.com/univ-smb-m1-isc-2023/tradingGame-web/master:latest

      - name: Push to GitHub Packages
        run: docker push docker.pkg.github.com/univ-smb-m1-isc-2023/tradingGame-web/master:latest
